### ISSUE TITLE
Footer relative links issue.

### ISSUE THREAD

**Issue by rafim888** [aemsites/888de#116]
On 888.de footer we have links to internal pages, the links on our current site are relavative.
We change some of the footer links, 
 
![image](https://github.com/aemsites/888de/assets/158305415/b5f3d5da-cd1d-4976-90f0-590f303cf3be)

in the EDS site (https://main--888de--aemsites.hlx.live/ >> https://eds-www.888.de/) to be relative (in the file https://888holdings.sharepoint.com/:w:/r/sites/888-eds/_layouts/15/Doc.aspx?sourcedoc=%7B41AAFAA0-8CB6-4BD6-BFD7-D88305688342%7D&file=footer.docx&action=default&mobileredirect=true , share point), with editing the link via Word’s widget, but it does not accept relative links
 
![image](https://github.com/aemsites/888de/assets/158305415/f0ebe592-7dca-4972-b773-1dd466a3424e)

originally inserted: “/banking/”.
When the footer was published via (Sidekick), the link was removed from the source code, this is what I get in “inspect element”
 
Both https://main--888de--aemsites.hlx.live/ & https://eds-www.888.de/
Is there a way to change links to relative ?

**Comment by helms-charity** [comment]
Hi @rafim888 ,
the Edge Delivery Service (formerly known as "Franklin") is smart, and should be automatically handling links that are entered using the project branch + hlx.page URL, and showing as relative on the published page. I will have a look at our 888 footer to see what's happening.

Here's an example from a previous project:
![image](https://github.com/aemsites/888de/assets/3883795/ba0d9461-6068-49b6-a921-2313bb4d4562)

**Comment by helms-charity** [comment]
I had a quick look, I am seeing the local paths on https://eds-dev-www.888.de/ where I edited (see screenshot). 

![image](https://github.com/aemsites/888de/assets/3883795/9e1c171c-cbf4-4961-8bc4-2acd6d231e96)

I do see an extra word on the 1st link, but I am thinking it might be because you have it open and are currently editing...?

![image](https://github.com/aemsites/888de/assets/3883795/9b063822-fd6d-44bb-a744-2a744fff86ca)

**Comment by rafim888** [comment]
10x Charity.
all clear now
