### ISSUE TITLE
Incorrect innerpage breadcrumbs

### ISSUE THREAD

**Issue by ByronA-888WHG** [aemsites/888de#203]
Hello,
Please look at the issues below

Issue 1 https://eds-www.888.de/sicherheit-datenschutz/nutzungsvereinbarung/
(Note: This was observed in all inner pages under Sicherheit & Datenschutz)
![issue](https://github.com/aemsites/888de/assets/165295931/db97c1c9-f0a5-4f59-967f-3edc705a8042)

Issue 2 https://eds-www.888.de/banking/abhebung/wie-abheben/
![issue 2](https://github.com/aemsites/888de/assets/165295931/018d2a12-67a3-44de-8ee4-6c656742564a)

Issue 3 https://eds-www.888.de/banking/einzahlung/einzahlungslimits/
![Issue 3](https://github.com/aemsites/888de/assets/165295931/27ef1b55-b4a2-4604-aaa6-e359d4c8cd3a)

Thank you!

**Comment by helms-charity** [comment]
Hi, I believe we talked about this with @rafim888 -- we are currently taking the "H1" element from each page to set the breadcrumb title, so that it is created automatically. 
Rafi -- is this still OK for the new site? Otherwise, it will be the responsibility of the page author to manually type in what the breadcrumb title should be for each page.

**Comment by ByronA-888WHG** [comment]
Hi @helms-charity,
Apologies for the confusion. Please disregard this.
Thank you!
